CMakeLists.txt

Only this code needs this flag. Using for the rest slowdowns fuzzing
significantly.

Move -fsanitize-coverage=trace-pc-guard back to the libfuzzer example

---

src/mutator.cc
src/mutator_test.cc

we need temporarily undo 142e08bf2a34d57d72e4619adeea4d7bab81a7d0

libFuzzer does not allow to use LLVMFuzzerMutate from CustomCrossover so

---

.travis.yml
CMakeLists.txt

Remove LIB_PROTO_MUTATOR_WITH_COVERAGE_FLAGS. It was added for OSS-Fuzz but turn
out to be unnecessary.

Disable ASAN by default, as it was unusual default behavior.

---

CMakeLists.txt

Building with --stdlib=libc++ may need this pthread.

Link protobuf with pthread.

---

src/mutator.cc

The build with GCC 7 fails with:
```
FAILED: obj/third_party/libprotobuf-mutator/libprotobuf-mutator/mutator.o
g++ -MMD -MF obj/third_party/libprotobuf-mutator/libprotobuf-mutator/mutator.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -I../.. -Igen -I../../third_party/libprotobuf-mutator/src -I../../third_party/protobuf/src …
```

Fix compilation with GCC 7

---

CMakeLists.txt
src/field_instance.h

Change assertion so that it doesn't cause a compilation error with
"-Wstring-conversion" compile flag. Add "-Wstring-conversion" to CMakeLists.txt
so that similar mistakes in the future will be caught here, rather than 
downstream.

Fix compile error in with -Wstring-conversion by changing error message in assertion

---

src/mutator.cc
src/mutator.h

Even messages without required fields can be deep enough to trigger stack
overflow.

Improve protection against stack overflow

---

src/field_instance.h
src/libfuzzer/libfuzzer_macro.cc
src/libfuzzer/libfuzzer_macro.h
src/mutator.cc
src/mutator.h
src/mutator_test.cc

This adds support for users of libprotobuf-mutator to supply per-field custom mutations in the form of a callback that can operate on the parent message.

Added custom field mutators.

---

CMakeLists.txt
libprotobuf-mutator.pc.in
src/CMakeLists.txt
src/libfuzzer/CMakeLists.txt

This adds the needed logic for "make install" to work along with creating a pkg-config file that is used to specify compiler and linker flags.

Added "make install" and pkg-config file.

---

src/libfuzzer/libfuzzer_mutator.cc
src/utf8_fix.cc

On Windows std::uniform_int_distribution does not accept uint8_t or
char32_t. Using them causes compilation failure.
In places where they are used, substitute uint16_t and char32_t,
respectively.
This patch should not change any functionality.

[NFC] Change types for in uniform_int_distribution for Windows

---

CMakeLists.txt
src/CMakeLists.txt

`TESTING` option can enable/disable builds of test so the project can be used as a library without redundant compilations
Also I've add `find_package(GTest)` line (maybe even delete cmake/external/googletest.cmake?), without it I cannot build:
`No rule to make target 'external.googletest/lib/libgtest.a', needed by 'src/mutator_test'.  Stop.`

Add flag for tests building

---

CMakeLists.txt

LIB_DIR is used by make install to set the install path of the static
libraries. It needs to be set even when testing is disabled.

Move LIB_DIR var outside of testing related if statement.

---

CMakeLists.txt
src/CMakeLists.txt
src/libfuzzer/CMakeLists.txt

This PR contains several fixes for `CMakeLists.txt` files for the following issues:
* Shared libraries were not installed due to lack of `LIBRARY DESTINATION` option in `install` command.
* `SOVERSION` was not set up, so only `.so` files were created, but `.so.*` were missing.
* Installation path for pkgconfig file had a typo and was not configurable (some Linux distributions prefer to use `/usr/lib(64)/pkgconfig` instead of `/usr/share/pkgconfig`).

Several cmake fixes

---

src/field_instance.h

it was a comparison with unsigned < 0, which is always false.
The error previously was:
[12/16] Building CXX object src/CMakeFiles/protobuf-mutator.dir/mutator.cc.oIn file included from /fuzzing/libprotobuf-mutator/src/mutator.cc:23:/fuzzing/libprotobuf-mutator/src/field_instance.h:149:22: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]    if (value->index < 0 || value->index >= value->count) GetDefault(value);        ~~~~~~~~~~~~ ^ ~1 warning generated.

Fix compile error/warning in src/field_instance.h

---

CMakeLists.txt
cmake/external/googletest.cmake
cmake/external/protobuf.cmake
src/CMakeLists.txt
src/libfuzzer/libfuzzer_mutator.cc
src/mutator_test.cc
src/no_mutator_test.cc
src/utf8_fix_test.cc
src/weighted_reservoir_sampler_test.cc

Fixes some issues with compiler flags not supported on MSVC (-Werror)
Also, Protobuf builds by default with [/MT](https://github.com/protocolbuffers/protobuf/blob/d9ccd0c0e6bbda9bf4476088eeb46b02d7dcd327/examples/CMakeLists.txt#L16), whereas LPM built by default
with /MD. Now, when `-DLIB_PROTO_MUTATOR_DOWNLOAD_PROTOBUF=On` or
`-DLIB_PROTO_MUTATOR_MSVC_STATIC_RUNTIME=On` are specified we build LPM with
/MT so LPM and Protobuf can properly link together.

Updates CMakeLists.txt to build for MSVC

---

src/libfuzzer/libfuzzer_macro.cc
src/libfuzzer/libfuzzer_macro.h
src/mutator.cc
src/mutator.h
src/mutator_test.cc

I have a use-case where multiple top-level proto message embed the same
submessage type.
I would like to be able to create a single mutator for the message type
instead of having to duplicate the logic everywhere.

Add global mutator support

---

src/mutator_test.cc
src/text_format.cc

As discussed in envoyproxy/envoy#10796, this will allow breaking wire-compatibility changes in the input proto. The pre-existing corpus will still function, but old fields will be ignored.
Risk: Typos in the text proto will cause the fuzzer to run on an incomplete proto. Previously, this would log an error message and skip fuzzing with that test case.
Testing: I'm not sure how to add it to `mutator_test.cc`. I manually tested that unknown text format files will be parsed without `ParseTextMessage` returning false.

Allow unknown fields in corpus parser

---

src/mutator_test.cc
src/text_format.cc

We need to fix AllowUnknownField implementation to respect SetRecursionLimit.
Issue #172

Temporarily dissable AllowUnknownField

---

src/mutator_test.cc
src/text_format.cc

The fix to protocol buffers was made in google3 and is now on Github: https://github.com/protocolbuffers/protobuf/commit/c05b55880fc7cf1ed8d118b21266fa4bf9c4cbf7#diff-af8c58a717e41f41544206e37b18de65R640
Is there anything else we need to do so we can update? From my understanding, libprotobufmutator does not use CMake to pull in the repository, it just finds it on the user's path.
Same changes as #170 
Fixes #172

Fix unknown fields

---

cmake/external/googletest.cmake
cmake/external/protobuf.cmake

Use https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html
module for determining whether child CMake will install libraries into
lib, lib64 or even somewhere else.
Fixes #131

Fix building on Fedora

---

CMakeLists.txt
libprotobuf-mutator.pc.in
libprotobuf-mutatorConfig.cmake.in
src/CMakeLists.txt
src/libfuzzer/CMakeLists.txt

- Fix pkgconfig to contain the library link directory flag
- Add CMake targets installation. Usage:
```
find_package(libprotobuf-mutator CONFIG REQUIRED)
target_link_libraries(main PRIVATE libprotobuf-mutator::protobuf-mutator libprotobuf-mutator::protobuf-mutator-libfuzzer)
```

Fix pkgconfig and add CMake targets installation

---

src/libfuzzer/libfuzzer_mutator.cc

Fix src\libfuzzer\libfuzzer_mutator.cc(93,44): error C4146: unary minus operator applied to unsigned type, result still unsigned

Refactor unary minus for unsigned type in MutateString

---

src/libfuzzer/libfuzzer_mutator.cc

LLVMFuzzerMutate was returning data marked as uninitialized, but it should be treated at initialized when running with the memory sanitzer.

Unpoison results from LLVMFuzzerMutate.

---

src/utf8_fix.cc

stdint.h is necessary for uint8_t.

Include header fixes.

---

CMakeLists.txt

Since `option()` was used it defaulted to OFF instead of the supplied string as `option()` is used for booleans only, resulting in `libprotobuf-mutator.pc` file being installed in `${prefix}/OFF/libprotobuf-mutator.pc` which is clearly undesirable. Change it to `set()` so the default value is properly stored and used.

Fix default PKG_CONFIG_PATH in CMakeLists.txt

---

.github/workflows/cmake-multi-platform.yml
cmake/external/googletest.cmake
cmake/external/protobuf.cmake
examples/libfuzzer/libfuzzer_bin_example.cc
examples/libfuzzer/libfuzzer_example.cc
src/field_instance.h
src/mutator.cc
src/mutator_test.cc

Avoid direct dependency on absl.

---

.github/workflows/cmake-multi-platform.yml
examples/libfuzzer/libfuzzer_bin_example.cc
examples/libfuzzer/libfuzzer_example.cc
src/field_instance.h
src/mutator.cc
src/mutator_test.cc

Support Ubuntu 24.04 out of the box (fixes #261)… while keeping support for more recent Protobuf intact

---

CMakeLists.txt

Will allow quicker builds (and without `liblzma-dev` installed) where libprotobuf-mutator is bundled.
CC @vitalybuka

Support `-DLIB_PROTO_MUTATOR_EXAMPLES:BOOL=OFF` to build without examples

---

.github/workflows/cmake-multi-platform.yml

This eases development in fork repositories, in particular :pray: 
CC @vitalybuka

Enable CI for non-master branches

---

.github/workflows/cmake-multi-platform.yml
CMakeLists.txt
README.md
examples/fuzzer_test.h
examples/libfuzzer/libfuzzer_example_test.cc
port/protobuf.h
src/field_instance.h
src/mutator.cc
src/mutator_test.cc
src/text_format.cc

[OSS-Fuzz is using Ubuntu 20.04](https://github.com/google/oss-fuzz/issues/13016). This pull request will help unlock use of libprotobuf-mutator in OSS-Fuzz with system Protobuf (i.e. of Ubuntu >=20.04) and eventually allow re-enabling compilation of libexpat upstream fuzzer `xml_lpm_fuzzer` that pull request https://github.com/libexpat/libexpat/pull/955 had to disable for a chance at a successful build in OSS-Fuzz. Thank you! :pray: 
CC @vitalybuka

Add support for Ubuntu 20.04 LTS (where OSS-Fuzz is at)

---

src/libfuzzer/libfuzzer_macro.cc
src/mutator.cc

As suggested to me by Coverity Scan. It's the only two suggestions it had about libprotobuf-mutator code, as part of a larger scan on libexpat…
@vitalybuka please review carefully, you know modern C++ better than I do. Thanks! :pray:

Use `std::move` in two more places?

---

.github/workflows/cmake-multi-platform.yml

Drop about-to-be-removed Ubuntu 20.04 from CI (fixes #282)
